# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/hawao/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),hawao)

$(call add-radio-file-sha1-checked,radio/bluetooth.img,e5b4c81ff687a8eb3b7801cd7d2c713de4cf78ae)
$(call add-radio-file-sha1-checked,radio/modem.img,f6d25fb618dcabf139da5f9398cb28569e651f3f)
$(call add-radio-file-sha1-checked,radio/abl.img,dcd42f874579e0e08f736d46b6df868906f57520)
$(call add-radio-file-sha1-checked,radio/devcfg.img,bd45b4ae7ca4a28155f371e02c4fa59a4695c51c)
$(call add-radio-file-sha1-checked,radio/dsp.img,e696f95a5b672f1b1355745ca05840b098cb6775)
$(call add-radio-file-sha1-checked,radio/fsg.img,32e7e3fbfb26e9ed274368add9d6c5d51503d184)
$(call add-radio-file-sha1-checked,radio/hyp.img,8ff3aecb113528553c3ad867b76b54daaf9983a5)
$(call add-radio-file-sha1-checked,radio/keymaster.img,3bb88cd1cdbd60d27b194d7df437b6c06aa1ae76)
$(call add-radio-file-sha1-checked,radio/logo.img,10b2e8ce75375d2f7c7305e60f743c67122612e6)
$(call add-radio-file-sha1-checked,radio/prov.img,8a2ea71c45b4c6b22e921400f7db4b3d4740fd2e)
$(call add-radio-file-sha1-checked,radio/qupfw.img,406c130921056a17f3bb4269fc171782aa053cc6)
$(call add-radio-file-sha1-checked,radio/rpm.img,f545542c5ca6686224b407f855617d44393a6d32)
$(call add-radio-file-sha1-checked,radio/storsec.img,6493e497b35abb7d2762433f32221a78105cbefa)
$(call add-radio-file-sha1-checked,radio/tz.img,42183ebf65fd64648b4ee0f5675c559a2dea2dad)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,be31bb876ccd755ebc926bb6de3f40e8456d8338)
$(call add-radio-file-sha1-checked,radio/xbl.img,aab5bf600dc5b228c8de6fb4b8f4d161a1b4f277)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,da563df33fcbbea6d1210ab2fa5dff0d46913cce)

endif
