# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/hawao/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),hawao)

$(call add-radio-file-sha1-checked,radio/bluetooth.img,31dfec64bbb80dd3a533fa44e884a7fb39612576)
$(call add-radio-file-sha1-checked,radio/modem.img,54c87ada6b718487a8ae3534be95ba64d6bcc9cd)
$(call add-radio-file-sha1-checked,radio/abl.img,55bc5588616e9918f15e6fae1da7788d2da954d2)
$(call add-radio-file-sha1-checked,radio/devcfg.img,12b47b034f4025ca4454831fc910b972382a4e45)
$(call add-radio-file-sha1-checked,radio/dsp.img,e696f95a5b672f1b1355745ca05840b098cb6775)
$(call add-radio-file-sha1-checked,radio/fsg.img,99734d676325b00157d6e8dff4c91ea4fde23c9c)
$(call add-radio-file-sha1-checked,radio/hyp.img,df4ce3da3b63e396c2faa977331091d23769ed91)
$(call add-radio-file-sha1-checked,radio/keymaster.img,a8a5ab49373781f97e6e86863530995fcb669db5)
$(call add-radio-file-sha1-checked,radio/logo.img,3fc72ac159c0a866c1594a1d7f1735485d000b43)
$(call add-radio-file-sha1-checked,radio/prov.img,4804e960dc26918660823ca34de1abd4e1b409f9)
$(call add-radio-file-sha1-checked,radio/qupfw.img,575638bffb80fc56f4ce4a801d1582f4d773c50d)
$(call add-radio-file-sha1-checked,radio/rpm.img,bf8fa9830c890ab83d0717672db5975e1d716832)
$(call add-radio-file-sha1-checked,radio/storsec.img,0f652b62ed0d2a9a46f7bf0a57f894db69739933)
$(call add-radio-file-sha1-checked,radio/tz.img,86c99f46eee9abca307299bcb3e304220e746e41)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,89595be92abfbe80a87c6f9845ed88c3183b6d4c)
$(call add-radio-file-sha1-checked,radio/xbl.img,23a2875c4e05e10ba4c88dffac9506743d6bedfa)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,f7c1100a53dbac8f543a39731f2d57c654c63b4a)

endif
